// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "Toad":return img`
....bbbb............
...b7777bbbb........
..bb7777711bbcc.....
..b11777771177cc....
..b11777777777bc....
..c7777777cccbbf....
.c77777bbbbcccbf....
c7777bbdddddccbf....
c77cbddddddcdcc.....
f7cccddcdddcdbc.....
fbcccdddcdddddf.....
fbcccdddddbbbdf.....
ffbbcbdddddddc......
.ffffbccddddff......
..fbddbccffbbff.....
..fdddb..ffbbbf.....
....................
....................
....................
....................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
